import { Inter } from "next/font/google";
import "./globals.css";

import CustomThemeProvider from "./CustomThemeProvider";

import StyledComponentsRegistry from "@/lib/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wakfu Strategy",
  description: "Generated by create next app",
  keywords: "Wakfu, jeu, MMORPG, guide, aide, stratégie, conseils, astuces",
  author: "Wakfu Strategy"
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <CustomThemeProvider>
            {children}
          </CustomThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
